# cp-2 ASSIGNMENT :

In [1]:
#11th EXPERIMENT:

def star(n):
    
    for i in range(0, n):
     
        for j in range(0, i+1):
         
            print("*",end="")
            
        print("\r")
n = 10
star(n)

*
**
***
****
*****
******
*******
********
*********
**********


In [4]:
#12th EXPERMENT:

string = input("enter a string: ")
i = int(input("enter no of char to be removed: "))
new_string =string.replace(string[0:i],"")
print(new_string)

enter a string: surya
enter no of char to be removed: 2
rya


In [5]:
#13th EXPERMENT:

input_string = input('Enter elements: ')
list1 = input_string.split()
for i in range(len(list1)):
    list1[i] = int(list1[i])
    if list1[i]%5==0:
        print(list1[i],end=" ")


Enter elements: 6


In [7]:
#14th EXPERMENT:

strg="Hi HiihihiHihiHihihi"
sub="H"

print("No. of times substring appears :",strg.count(sub))

No. of times substring appears : 4


In [8]:
#15th EXPERMENT:

def numbers(n):
    
    for i in range(1, n):
     
        for j in range(1, i+1):
         
            print(i,end="")
            
        print("\r")
n = 10
numbers(n)

1
22
333
4444
55555
666666
7777777
88888888
999999999


# TUPLES:



### 1st Experiment:
 ##### Python program to Find the size of a Tuple:

In [11]:


Tuple1 = ("E","W","Z", 54,79,100)
Tuple2 = ("SRIRAM", "VELAN", "SURYA", "poda", "akilan", "katta")
Tuple3 = ((78, "Roar"), ( 2, "King"), (100, "Last"), (65, "Rock"),( 7, "Feast"))

print("Size of Tuple1: " + str(Tuple1.__sizeof__()) + "bytes")
print("Size of Tuple2: " + str(Tuple2.__sizeof__()) + "bytes")
print("Size of Tuple3: " + str(Tuple3.__sizeof__()) + "bytes")


Size of Tuple1: 72bytes
Size of Tuple2: 72bytes
Size of Tuple3: 64bytes



### Python – Maximum and Minimum K elements in Tuple:

In [30]:
my_tuple = (20, 755, 556, 10, 60, 78)
print("The tuple is : ")
print(my_tuple)
K = 1
print("The value of K has been initialized to ")
print(K)
my_result = []
my_tuple = list(my_tuple)
temp = sorted(my_tuple)
for idx, val in enumerate(temp):
    if idx < K or idx >= len(temp) - K:
         my_result.append(val)
my_result = tuple(my_result)
print("The result is : " )
print(my_result)


The tuple is : 
(20, 755, 556, 10, 60, 78)
The value of K has been initialized to 
1
The result is : 
(10, 755)



### Python – Sum of tuple elements:

In [44]:
numTuple = (20, 40, 65, 75, 80, 220)
print("Tuple Items = ", numTuple)

tupleSum = sum(numTuple)
print("\nThe Sum of numTuple Tuple Items = ", tupleSum)

Tuple Items =  (20, 40, 65, 75, 80, 220)

The Sum of numTuple Tuple Items =  500


# SET:



### Find the size of a Set in Python:

In [7]:
set1 = {"E","W","Z", 54,79,100}
set2 = {"SRIRAM", "VELAN", "SURYA", "RAJ MOHAN", "Rajesh", "venkat"}
set3 = {(78, "Roar"), ( 2, "King"), (100, "Last"), (65, "Rock"),( 7, "Feast")}

print("Size of set1: " + str(set1.__sizeof__()) + "bytes")
print("Size of set2: " + str(set2.__sizeof__()) + "bytes")
print("Size of set3: " + str(set3.__sizeof__()) + "bytes")


Size of set1: 712bytes
Size of set2: 712bytes
Size of set3: 712bytes



### Iterate over a set in Python:

In [8]:
iterate = set("SRIRAM")

for val in iterate:
    print(val)


I
R
M
S
A


# MATRIX:


### Assigning Subsequent Rows to Matrix first row elements:

In [34]:
my_list=[[1,3,5],[2,4,6],[7,9,11],[10,20,30]]
print("my list :"+str(my_list))
result={my_list[0][val] : my_list[val+1] for val in range(len(my_list)-1)}
print("The matrix : " +str(result))

my list :[[1, 3, 5], [2, 4, 6], [7, 9, 11], [10, 20, 30]]
The matrix : {1: [2, 4, 6], 3: [7, 9, 11], 5: [10, 20, 30]}



### Adding and Subtracting Matrices in Python:

In [33]:
import numpy as np
A = np.array([[2,6],[5,6]])
B = np.array([[2,2],[6,8]])
print("elments in A")
print(A)
print("elments in B")
print(B)
print("addition of two matrix")
print(np.add(A,B))
print("subtraction of two matrics")
print(np.subtract(A,B))

elments in A
[[2 6]
 [5 6]]
elments in B
[[2 2]
 [6 8]]
addition of two matrix
[[ 4  8]
 [11 14]]
subtraction of two matrics
[[ 0  4]
 [-1 -2]]


# Function:


### How to get list of parameters name from a function in Python:

In [38]:
def function(a, b,c,d):
    return a**b**c**d
import inspect
print(inspect.signature(function9))

(a, b, c, d)



### How to Print Multiple Arguments in Python:

In [9]:
def student(student_name,dob):
     print("STUDENT DETAILS : " , student_name + ',' + dob)
student("SRIRAM" , "13/10/2003")
student("VELAN" , "12/12/2003")
student("SURYA" , "11/10/2003")

STUDENT DETAILS :  SRIRAM,13/10/2003
STUDENT DETAILS :  VELAN,12/12/2003
STUDENT DETAILS :  SURYA,11/10/2003


# DICTIONARY:


### Sort Python Dictionaries by Key or Value:

In [10]:
a={10:'sugar',20:'salt',50:'chips',80:'pepper'}
a=dict(sorted(a.items()))
print(a)

{10: 'sugar', 20: 'salt', 50: 'chips', 80: 'pepper'}



### Python dictionary with keys having multiple inputs:

In [1]:
dict1 = {}
a, b, c = 10, 20, 30
dict1[a, b, c] = a + b - c

a, b, c = 40, 50, 60
dict1[a, b, c] = a + b - c

print("The dictionary is :")
print(dict1)

The dictionary is :
{(10, 20, 30): 0, (40, 50, 60): 30}


# STRING:

## 1st Experiment:
### Python program to check whether the string is Symmetrical or Palindrome:

In [2]:
string=input("Enter a string :")
rev=string[::-1]

if string==rev:
    print("It is palindrome")
else:
    print("It is not a palindrome")


Enter a string :SRIRAM
It is not a palindrome



### Reverse words in a given String in Python:

In [3]:
string="SRIRAM"
new=''
for i in string.split():
    new+=i[::-1]+' '
    
print(new)

MARIRS 



### Ways to remove i’th character from string in Python:

In [4]:
str1 = "helloishello"
print ("The original string is : " + str1)
z = str(input("Which character you want to remove ?"))
new = str1.replace(z, '', 1)
print ("The string after removal of i'th character(works) : " + new)

The original string is : helloishello
Which character you want to remove ?i
The string after removal of i'th character(works) : helloshello


# LIST:


### Python program to interchange first and last elements in a list:

In [5]:
l=[]
length=int(input("Enter list size :"))
for i in range(0,length):
    e=int(input("Enter element :"))
    l.append(e)

l[0],l[length-1]=l[length-1],l[0]
print(l)

Enter list size :3
Enter element :123
Enter element :456
Enter element :456
[456, 456, 123]



### Python program to swap two elements in a list:

In [6]:
a=[9,99]
a[0],a[len(a)-1]=a[len(a)-1],a[0]
print(l)

[456, 456, 123]



### Ways to find length of list:

In [68]:
s=[34,40,50,66]
count=0
for i in s:
    count+=1   
print("Length of list :",count)

Length of list : 4



### Maximum of two numbers in Python:

In [7]:
def maximum(a, b):

    if a >= b:
        return a
    else:
        return b

a = 20
b = 40
print(maximum(a, b))


40



### Minimum of two numbers in Python:

In [74]:
def minimum(a, b):

    if a >= b:
        return a
    else:
        return b

a = 10
b = 50
print(minimum(a, b))


50
